export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const IS_LOGIN = 'IS_LOGIN';
export const IS_LOGIN_SUCCESS = 'IS_LOGIN_SUCCESS';
export const IS_LOGIN_FAILURE = 'IS_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const MY_WORD_BOOK_LIST = 'MY_WORD_BOOK_LIST';
export const MY_WORD_BOOK_LIST_SUCCESS = 'MY_WORD_BOOK_LIST_SUCCESS';
export const MY_WORD_BOOK_LIST_FAILURE = 'MY_WORD_BOOK_LIST_FAILURE';

export const MY_WORD_BOOK_SHOW = 'MY_WORD_BOOK_SHOW';
export const MY_WORD_BOOK_SHOW_SUCCESS = 'MY_WORD_BOK_SHOW_SUCCESS';
export const MY_WORD_BOOK_SHOW_FAILURE = 'MY_WORD_BOOK_SHOW_FAILURE';