export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const MY_WORD_BOOK_LIST = 'MY_WORD_BOOK_LIST';
export const MY_WORD_BOOK_LIST_SUCCESS = 'MY_WORD_BOOK_LIST_SUCCESS';
export const MY_WORD_BOOK_LIST_FAILURE = 'MY_WORD_BOOK_LIST_FAILURE';